# Generated by Django 3.1.7 on 2021-07-08 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_remove_board_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
