# Generated by Django 3.1.7 on 2021-07-08 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_board_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='pub_date',
            field=models.DateTimeField(),
        ),
    ]
